function a = PlotFigure1( elcentro_t, d_lsim_el, d_el_zoh, d_el_foh, d_el_newmark, d_el_rk4,d_el_wilson,d_el_central )
mFigure1 = figure(1);
subplot(3,2,1);
plot(elcentro_t,d_lsim_el,elcentro_t,d_el_zoh);
title('El Centro Displacement - Piecewise Constant Method vs lsim');
legend('MATLAB lsim','Piecewise Constant');
xlabel('Time');
ylabel('Displacement');
subplot(3,2,2);
plot(elcentro_t,d_lsim_el,elcentro_t,d_el_foh);
title('El Centro Displacement - Piecewise Linear Method vs lsim');
legend('MATLAB lsim','Piecewise Linear');
xlabel('Time');
ylabel('Displacement');
subplot(3,2,3);
plot(elcentro_t,d_lsim_el,elcentro_t,d_el_newmark);
title('El Centro Displacement - Newmark vs lsim');
legend('MATLAB lsim','Newmark');
xlabel('Time');
ylabel('Displacement');
subplot(3,2,4);
plot(elcentro_t,d_lsim_el,elcentro_t,d_el_rk4);
title('El Centro Displacement - Rk4 vs lsim');
legend('MATLAB lsim','Rk4');
xlabel('Time');
ylabel('Displacement');
subplot(3,2,5);
plot(elcentro_t,d_lsim_el,elcentro_t,d_el_wilson);
title('El Centro Displacement - Wilson vs lsim');
legend('MATLAB lsim','Wilson');
xlabel('Time');
ylabel('Displacement');
subplot(3,2,6);
plot(elcentro_t,d_lsim_el,elcentro_t,d_el_central);
title('El Centro Displacement - Central vs lsim');
legend('MATLAB lsim','Central');
xlabel('Time');
ylabel('Displacement');
set(mFigure1, 'Position', [0,0,800,800]);
a = 1;
end

