function [ a ] = PlotVelHarmonicExcitationPlots( t_h, v_lsim_h, v_h_zoh, v_h_foh, v_h_newmark, v_h_rk4, v_h_wilson, v_h_central )
mFigure6 = figure(6);
subplot(3,2,1);
plot(t_h,v_lsim_h,t_h,v_h_zoh);
title('Harmonic Velocity Plots - Piecewise Constant Method vs lsim');
legend('MATLAB lsim','Piecewise Constant');
xlabel('Time');
ylabel('Velocity');
subplot(3,2,2);
plot(t_h,v_lsim_h,t_h,v_h_foh);
title('Harmonic Velocity Plots - Piecewise Linear Method vs lsim');
legend('MATLAB lsim','Piecewise Linear');
xlabel('Time');
ylabel('Velocity');
subplot(3,2,3);
plot(t_h,v_lsim_h,t_h,v_h_newmark);
title('Harmonic Velocity Plots - Newmark vs lsim');
legend('MATLAB lsim','Newmark');
xlabel('Time');
ylabel('Velocity');
subplot(3,2,4);
plot(t_h,v_lsim_h,t_h,v_h_rk4);
title('Harmonic Velocity Plots - Rk4 vs lsim');
legend('MATLAB lsim','Rk4');
xlabel('Time');
ylabel('Velocity');
subplot(3,2,5);
plot(t_h,v_lsim_h,t_h,v_h_wilson);
title('Harmonic Velocity Plots - Wilson vs lsim');
legend('MATLAB lsim','Wilson');
xlabel('Time');
ylabel('Velocity');
subplot(3,2,6);
plot(t_h,v_lsim_h,t_h,v_h_central);
title('Harmonic Velocity Plots - Central vs lsim');
legend('MATLAB lsim','Central');
xlabel('Time');
ylabel('Velocity');
set(mFigure6, 'Position', [0,0,800,800]);
a = 1;
end

